[window]
padding = { x = 6, y = 6 }

[font]
size = 12
normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }
bold = { family = "JetBrainsMono Nerd Font", style = "Bold" }
italic = { family = "JetBrainsMono Nerd Font", style = "Italic" }
bold_italic = { family = "JetBrainsMono Nerd Font", style = "Bold Italic" }

[general]
import = [
    "~/.config/alacritty/themes/afflabio-light.toml"
]
