#!/usr/bin/env bash

MEDIA_KEYS="org.gnome.settings-daemon.plugins.media-keys"
CUSTOM_KB="$MEDIA_KEYS.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings"

# wezterm -> Super+Enter
gsettings set $CUSTOM_KB/custom0/ name "Wezterm"
gsettings set $CUSTOM_KB/custom0/ command "wezterm"
gsettings set $CUSTOM_KB/custom0/ binding "<Super>Return"

# librewolf -> Super+L
gsettings set $CUSTOM_KB/custom1/ name "Librewolf"
gsettings set $CUSTOM_KB/custom1/ command "librewolf"
gsettings set $CUSTOM_KB/custom1/ binding "<Super>l"

# brave -> Super+B
gsettings set $CUSTOM_KB/custom2/ name "Brave"
gsettings set $CUSTOM_KB/custom2/ command "brave-browser"
gsettings set $CUSTOM_KB/custom2/ binding "<Super>b"

# chromium -> Super+C
gsettings set $CUSTOM_KB/custom3/ name "Chromium"
gsettings set $CUSTOM_KB/custom3/ command "flatpak run org.chromium.Chromium"
gsettings set $CUSTOM_KB/custom3/ binding "<Super>c"

# gnome-terminal -> Super+T
gsettings set $CUSTOM_KB/custom4/ name "GNOME Terminal"
gsettings set $CUSTOM_KB/custom4/ command "gnome-terminal"
gsettings set $CUSTOM_KB/custom4/ binding "<Super>t"

# applications dir -> CTRL+SHIFT+A
gsettings set $CUSTOM_KB/custom5/ name "Open Applications"
gsettings set $CUSTOM_KB/custom5/ command "xdg-open $HOME/Applications/"
gsettings set $CUSTOM_KB/custom5/ binding "<CTRL><SHIFT>A"

# Set all keybindings as active
gsettings set $MEDIA_KEYS custom-keybindings "[
'/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/',
'/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom1/',
'/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom2/',
'/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom3/',
'/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom4/',
'/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom5/'
]"
