font_family JetBrainsMono NF Regular
bold_font JetBrainsMono NF Bold
italic_family JetBrainsMono NF Italic
bold_italic_font JetBrainsMono NF Bold Italic

background_image ~/terminal.png
background_image_layout scaled
background_image_linear no
background_tint 0.9
dim_opacity 0.9

font_size 12
modify_font cell_height 180%
modify_font strikethrough_position 150%

cursor_blink_interval 0

draw_minimal_borders yes
window_margin_width 0
window_padding_width 5 5 0 5
hide_window_decorations yes
# wayland_titlebar_color background
remember_window_size yes
initial_window_width 1680
initial_window_height 1200
enable_audio_bell no

# BEGIN_KITTY_THEME
# include eldritch-theme.conf
include current-theme.conf
# END_KITTY_THEME
