#!/bin/bash

NEW_HOSTNAME=$1
CURRENT_HOSTNAME=$(hostname)

if [ -z "$1" ]; then
  echo "Please provide the hostname"
  exit 1
fi

echo "To change the hostname, follow the steps below:"
echo "- Run this command:"
echo "  $ sudo hostnamectl set-hostname $NEW_HOSTNAME"

echo "- Then run:"
echo "  $ sudo vim /etc/hosts"
echo "- And replace \`127.0.1.1 $CURRENT_HOSTNAME\` with \`127.0.1.1 $NEW_HOSTNAME\`"

echo "- You may need to log out/in or reboot for all changes to apply."

