#!/usr/bin/env bash

rm -rf $HOME/.tmux
mkdir $HOME/.tmux
ln -s $DOTFILES/tmux/tmux-save.sh $HOME/.tmux/tmuxsave.sh
ln -s $DOTFILES/tmux/tmux-start.sh $HOME/.tmux/tmuxstart.sh
ln -s $DOTFILES/tmux/tmux-restore.sh $HOME/.tmux/tmuxrestore.sh
chmod +x $HOME/.tmux/tmuxsave.sh
chmod +x $HOME/.tmux/tmuxstart.sh
chmod +x $HOME/.tmux/tmuxrestore.sh

# Aliases
ALIASES="$HOME/.bash_aliases"
LINE='[ -f ~/.tmux/tmuxaliases ] && source ~/.tmux/tmuxaliases'

# create the symlink
ln -s $DOTFILES/tmux/tmux-aliases $HOME/.tmux/tmuxaliases

# make sure the file exists
[ -f "$ALIASES" ] || : > "$ALIASES"

# append only if not already present
grep -qxF "$LINE" "$ALIASES" || echo "$LINE" >> "$ALIASES"

