#!/usr/bin/env bash
# Run the restore script generated by tmux-save.sh

script="${1:-$HOME/.tmux-sessions.sh}"
if [ -x "$script" ]; then
  "$script"
  echo "Tip: attach with tmux attach -t <session> or your ts alias."
else
  echo "No restore script found at $script" >&2
  exit 1
fi

